version: '3.1'
services:
  api-service:
    image: bookwheelapi
    ports:
      - 8080:8080
      - 443:443
    depends_on:
      - "sqlserver"
    environment:
      ConnectionStrings_MSSQL: ${cnstring}

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: Developer